//Code Generated by Jenga.NET 
            using System.Drawing;
            using System.Windows.Forms;

			namespace CRM.Dialogs
			{
			partial class Frm_Customer
			{

			private System.ComponentModel.IContainer components = null;

			protected override void Dispose(bool disposing)
			{
			if (disposing && (components != null))
			{
			components.Dispose();
			}
			base.Dispose(disposing);
			}

			#region Windows Form Designer generated code

			private void InitializeComponent()
			{
			this.components = new System.ComponentModel.Container();
			this.Alert = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
			this.validationProvider = new Kimtoo.ValidationProvider.ValidationProvider();
			this.bindingProvider = new Kimtoo.BindingProvider.BindingProvider();
            this.themeProvider = new Kimtoo.ThemeProvider.ThemeProvider();
			this.btnAdd = new System.Windows.Forms.Button();
			this.btnCancel = new System.Windows.Forms.Button();
			this.AppBar = new Bunifu.Utils.BunifuAppBar();
			this.pnlContent = new System.Windows.Forms.Panel();
			this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
		    this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
			this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
			this.lblName = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject NamevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject NameBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblPhone = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject PhonevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject PhoneBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblEmail = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject EmailvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject EmailBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblDepartment = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject DepartmentvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject DepartmentBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtDepartment = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblCity = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject CityvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject CityBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtCity = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblState = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject StatevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject StateBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtState = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblZip = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject ZipvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject ZipBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtZip = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblCountry = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject CountryvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject CountryBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtCountry = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblAddress1 = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject Address1validationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject Address1BindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtAddress1 = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblAddress2 = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject Address2validationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject Address2BindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtAddress2 = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblType = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject TypevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject TypeBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.cmbType = new Bunifu.UI.WinForms.BunifuDropdown();
this.lblNotes = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject NotesvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject NotesBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtNotes = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblCreatedAt = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject CreatedAtvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject CreatedAtBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.dtCreatedAt = new Bunifu.UI.WinForms.BunifuDatePicker();
this.lblBottom = new System.Windows.Forms.Label();
//init

			this.SuspendLayout();
			//
			// AppBar
			//
			this.AppBar.BackColor = System.Drawing.Color.DodgerBlue;
			this.AppBar.ControlBoxColor = System.Drawing.Color.WhiteSmoke;
			this.AppBar.ControlBoxColorActive = System.Drawing.Color.White;
			this.AppBar.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
			this.AppBar.ForeColor = System.Drawing.Color.White;
			this.AppBar.Dock = System.Windows.Forms.DockStyle.Top;
			this.validationProvider.SetLink(this.AppBar, null);
			this.bindingProvider.SetLink(this.AppBar, null);
			this.AppBar.Location = new System.Drawing.Point(3, 5);
			this.AppBar.Name = "Customer";
			this.AppBar.Size = new System.Drawing.Size(574, 46);
			this.AppBar.TabIndex = 6;
			this.AppBar.Title = "Customer";
			this.AppBar.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
			//
			// pnlContent
			//
			this.pnlContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.validationProvider.SetLink(this.pnlContent, null);
			this.bindingProvider.SetLink(this.pnlContent, null);
			this.pnlContent.Location = new System.Drawing.Point(3, 51);
			this.pnlContent.Name = "pnlContent";
			this.pnlContent.Size = new System.Drawing.Size(590, 515);
			this.pnlContent.TabIndex = 7;
			this.pnlContent.AutoScroll = true;
			//
			// btnAdd
			//
			this.btnAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnAdd.BackColor = System.Drawing.Color.DodgerBlue;
			this.btnAdd.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
			this.btnAdd.FlatAppearance.BorderSize = 2;
			this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnAdd.ForeColor = System.Drawing.Color.White;
			this.validationProvider.SetLink(this.btnAdd, null);
			this.bindingProvider.SetLink(this.btnAdd, null);
			this.btnAdd.Location = new System.Drawing.Point(435, 1040);
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Size = new System.Drawing.Size(115, 40);
			this.btnAdd.TabIndex = 12;
			this.btnAdd.Text = "SAVE";
			this.btnAdd.UseVisualStyleBackColor = false;
			this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
			//
			// btnCancel
			//
			this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnCancel.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
			this.btnCancel.FlatAppearance.BorderSize = 2;
			this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnCancel.ForeColor = System.Drawing.Color.DodgerBlue;
			this.validationProvider.SetLink(this.btnCancel, null);
			this.bindingProvider.SetLink(this.btnCancel, null);
			this.btnCancel.Location = new System.Drawing.Point(335,  1040);
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Size = new System.Drawing.Size(94, 40);
			this.btnCancel.TabIndex = 13;
			this.btnCancel.Text = "CANCEL";
			this.btnCancel.UseVisualStyleBackColor = false;
			this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
			//
			// bunifuFormDock
			//
			this.bunifuFormDock.AllowFormDragging = true;
			this.bunifuFormDock.AllowFormDropShadow = true;
			this.bunifuFormDock.AllowFormResizing = true;
			this.bunifuFormDock.AllowHidingBottomRegion = true;
			this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
			this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
			this.bunifuFormDock.ContainerControl = this;
			this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
			this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
			this.bunifuFormDock.DockingOptions.DockAll = true;
			this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
			this.bunifuFormDock.DockingOptions.DockBottomRight = true;
			this.bunifuFormDock.DockingOptions.DockFullScreen = true;
			this.bunifuFormDock.DockingOptions.DockLeft = true;
			this.bunifuFormDock.DockingOptions.DockRight = true;
			this.bunifuFormDock.DockingOptions.DockTopLeft = true;
			this.bunifuFormDock.DockingOptions.DockTopRight = true;
			this.bunifuFormDock.FormDraggingOpacity = 0.9D;
			this.bunifuFormDock.ParentForm = this;
			this.bunifuFormDock.ShowCursorChanges = true;
			this.bunifuFormDock.ShowDockingIndicators = true;
		    this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = false;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false; 
			//
			// Alert
			//
			this.Alert.AllowDragging = false;
			this.Alert.AllowMultipleViews = true;
			this.Alert.ClickToClose = true;
			this.Alert.DoubleClickToClose = true;
			this.Alert.DurationAfterIdle = 3000;
			this.Alert.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.ErrorOptions.ActionBorderRadius = 1;
			this.Alert.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.ErrorOptions.BackColor = System.Drawing.Color.White;
			this.Alert.ErrorOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
			this.Alert.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.ErrorOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.ErrorOptions.IconLeftMargin = 12;
			this.Alert.FadeCloseIcon = false;
			this.Alert.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
			this.Alert.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.ActionBorderRadius = 1;
			this.Alert.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.InformationOptions.BackColor = System.Drawing.Color.White;
			this.Alert.InformationOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.InformationOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.InformationOptions.IconLeftMargin = 12;
			this.Alert.Margin = 10;
			this.Alert.MaximumSize = new System.Drawing.Size(0, 0);
			this.Alert.MaximumViews = 7;
			this.Alert.MessageRightMargin = 15;
			this.Alert.MinimumSize = new System.Drawing.Size(0, 0);
			this.Alert.ShowBorders = false;
			this.Alert.ShowCloseIcon = false;
			this.Alert.ShowIcon = true;
			this.Alert.ShowShadows = true;
			this.Alert.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.SuccessOptions.ActionBorderRadius = 1;
			this.Alert.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.SuccessOptions.BackColor = System.Drawing.Color.White;
			this.Alert.SuccessOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
			this.Alert.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.SuccessOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.SuccessOptions.IconLeftMargin = 12;
			this.Alert.ViewsMargin = 7;
			this.Alert.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.WarningOptions.ActionBorderRadius = 1;
			this.Alert.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.WarningOptions.BackColor = System.Drawing.Color.White;
			this.Alert.WarningOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
			this.Alert.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.WarningOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.WarningOptions.IconLeftMargin = 12;
			this.Alert.ZoomCloseIcon = true;

			
                    //
                    // lblName
                    //
                    this.lblName.AutoSize = true;
                    this.lblName.Location = new System.Drawing.Point(25, 30);
                    this.lblName.Name = "lblName";
                    this.lblName.Text = "Name*";
                    this.themeProvider.SetLink(this.lblName, null);
                    this.pnlContent.Controls.Add(this.lblName);

                    

                NamevalidationObject.Optional = false;
                NamevalidationObject.Regex = "^[a-z ,.'-]+$";
                NamevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            NameBindingObject.Data = "Name";
            NameBindingObject.TwoWay = true;

            
                      this.txtName.Location = new System.Drawing.Point(150, 20);
                     
                    this.txtName.Size = new System.Drawing.Size(400, 39);
                     
                this.txtName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtName.PlaceholderText = "Enter Name";
                this.txtName.ReadOnly = false;
                this.txtName.BackColor = System.Drawing.Color.White;
                 NamevalidationObject.PropertyName = "Text";
                 NameBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtName, NamevalidationObject);
                this.bindingProvider.SetLink(this.txtName, NameBindingObject);
                this.themeProvider.SetLink(this.txtName, null);
                this.pnlContent.Controls.Add(this.txtName);

                
                    //
                    // lblPhone
                    //
                    this.lblPhone.AutoSize = true;
                    this.lblPhone.Location = new System.Drawing.Point(25, 100);
                    this.lblPhone.Name = "lblPhone";
                    this.lblPhone.Text = "Phone";
                    this.themeProvider.SetLink(this.lblPhone, null);
                    this.pnlContent.Controls.Add(this.lblPhone);

                    

                PhonevalidationObject.Optional = true;
                PhonevalidationObject.Regex = "^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$";
                PhonevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            PhoneBindingObject.Data = "Phone";
            PhoneBindingObject.TwoWay = true;

            
                      this.txtPhone.Location = new System.Drawing.Point(150, 90);
                     
                    this.txtPhone.Size = new System.Drawing.Size(400, 39);
                     
                this.txtPhone.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtPhone.PlaceholderText = "Enter Phone";
                this.txtPhone.ReadOnly = false;
                this.txtPhone.BackColor = System.Drawing.Color.White;
                 PhonevalidationObject.PropertyName = "Text";
                 PhoneBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtPhone, PhonevalidationObject);
                this.bindingProvider.SetLink(this.txtPhone, PhoneBindingObject);
                this.themeProvider.SetLink(this.txtPhone, null);
                this.pnlContent.Controls.Add(this.txtPhone);

                
                    //
                    // lblEmail
                    //
                    this.lblEmail.AutoSize = true;
                    this.lblEmail.Location = new System.Drawing.Point(25, 170);
                    this.lblEmail.Name = "lblEmail";
                    this.lblEmail.Text = "Email";
                    this.themeProvider.SetLink(this.lblEmail, null);
                    this.pnlContent.Controls.Add(this.lblEmail);

                    

                EmailvalidationObject.Optional = true;
                EmailvalidationObject.Regex = "(?:[a-z0-9!#$%&'*+/=?^_`{|}'-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}'-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
                EmailvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            EmailBindingObject.Data = "Email";
            EmailBindingObject.TwoWay = true;

            
                      this.txtEmail.Location = new System.Drawing.Point(150, 160);
                     
                    this.txtEmail.Size = new System.Drawing.Size(400, 39);
                     
                this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtEmail.PlaceholderText = "Enter Email";
                this.txtEmail.ReadOnly = false;
                this.txtEmail.BackColor = System.Drawing.Color.White;
                 EmailvalidationObject.PropertyName = "Text";
                 EmailBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtEmail, EmailvalidationObject);
                this.bindingProvider.SetLink(this.txtEmail, EmailBindingObject);
                this.themeProvider.SetLink(this.txtEmail, null);
                this.pnlContent.Controls.Add(this.txtEmail);

                
                    //
                    // lblDepartment
                    //
                    this.lblDepartment.AutoSize = true;
                    this.lblDepartment.Location = new System.Drawing.Point(25, 240);
                    this.lblDepartment.Name = "lblDepartment";
                    this.lblDepartment.Text = "Department";
                    this.themeProvider.SetLink(this.lblDepartment, null);
                    this.pnlContent.Controls.Add(this.lblDepartment);

                    

                DepartmentvalidationObject.Optional = true;
                DepartmentvalidationObject.Regex = "";
                DepartmentvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            DepartmentBindingObject.Data = "Department";
            DepartmentBindingObject.TwoWay = true;

            
                      this.txtDepartment.Location = new System.Drawing.Point(150, 230);
                     
                    this.txtDepartment.Size = new System.Drawing.Size(400, 39);
                     
                this.txtDepartment.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtDepartment.PlaceholderText = "Enter Department";
                this.txtDepartment.ReadOnly = false;
                this.txtDepartment.BackColor = System.Drawing.Color.White;
                 DepartmentvalidationObject.PropertyName = "Text";
                 DepartmentBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtDepartment, DepartmentvalidationObject);
                this.bindingProvider.SetLink(this.txtDepartment, DepartmentBindingObject);
                this.themeProvider.SetLink(this.txtDepartment, null);
                this.pnlContent.Controls.Add(this.txtDepartment);

                
                    //
                    // lblCity
                    //
                    this.lblCity.AutoSize = true;
                    this.lblCity.Location = new System.Drawing.Point(25, 310);
                    this.lblCity.Name = "lblCity";
                    this.lblCity.Text = "City";
                    this.themeProvider.SetLink(this.lblCity, null);
                    this.pnlContent.Controls.Add(this.lblCity);

                    

                CityvalidationObject.Optional = true;
                CityvalidationObject.Regex = "";
                CityvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            CityBindingObject.Data = "City";
            CityBindingObject.TwoWay = true;

            
                      this.txtCity.Location = new System.Drawing.Point(150, 300);
                     
                    this.txtCity.Size = new System.Drawing.Size(400, 39);
                     
                this.txtCity.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtCity.PlaceholderText = "Enter City";
                this.txtCity.ReadOnly = false;
                this.txtCity.BackColor = System.Drawing.Color.White;
                 CityvalidationObject.PropertyName = "Text";
                 CityBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtCity, CityvalidationObject);
                this.bindingProvider.SetLink(this.txtCity, CityBindingObject);
                this.themeProvider.SetLink(this.txtCity, null);
                this.pnlContent.Controls.Add(this.txtCity);

                
                    //
                    // lblState
                    //
                    this.lblState.AutoSize = true;
                    this.lblState.Location = new System.Drawing.Point(25, 380);
                    this.lblState.Name = "lblState";
                    this.lblState.Text = "State";
                    this.themeProvider.SetLink(this.lblState, null);
                    this.pnlContent.Controls.Add(this.lblState);

                    

                StatevalidationObject.Optional = true;
                StatevalidationObject.Regex = "";
                StatevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            StateBindingObject.Data = "State";
            StateBindingObject.TwoWay = true;

            
                      this.txtState.Location = new System.Drawing.Point(150, 370);
                     
                    this.txtState.Size = new System.Drawing.Size(400, 39);
                     
                this.txtState.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtState.PlaceholderText = "Enter State";
                this.txtState.ReadOnly = false;
                this.txtState.BackColor = System.Drawing.Color.White;
                 StatevalidationObject.PropertyName = "Text";
                 StateBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtState, StatevalidationObject);
                this.bindingProvider.SetLink(this.txtState, StateBindingObject);
                this.themeProvider.SetLink(this.txtState, null);
                this.pnlContent.Controls.Add(this.txtState);

                
                    //
                    // lblZip
                    //
                    this.lblZip.AutoSize = true;
                    this.lblZip.Location = new System.Drawing.Point(25, 450);
                    this.lblZip.Name = "lblZip";
                    this.lblZip.Text = "Zip";
                    this.themeProvider.SetLink(this.lblZip, null);
                    this.pnlContent.Controls.Add(this.lblZip);

                    

                ZipvalidationObject.Optional = true;
                ZipvalidationObject.Regex = "";
                ZipvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            ZipBindingObject.Data = "Zip";
            ZipBindingObject.TwoWay = true;

            
                      this.txtZip.Location = new System.Drawing.Point(150, 440);
                     
                    this.txtZip.Size = new System.Drawing.Size(400, 39);
                     
                this.txtZip.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtZip.PlaceholderText = "Enter Zip";
                this.txtZip.ReadOnly = false;
                this.txtZip.BackColor = System.Drawing.Color.White;
                 ZipvalidationObject.PropertyName = "Text";
                 ZipBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtZip, ZipvalidationObject);
                this.bindingProvider.SetLink(this.txtZip, ZipBindingObject);
                this.themeProvider.SetLink(this.txtZip, null);
                this.pnlContent.Controls.Add(this.txtZip);

                
                    //
                    // lblCountry
                    //
                    this.lblCountry.AutoSize = true;
                    this.lblCountry.Location = new System.Drawing.Point(25, 520);
                    this.lblCountry.Name = "lblCountry";
                    this.lblCountry.Text = "Country";
                    this.themeProvider.SetLink(this.lblCountry, null);
                    this.pnlContent.Controls.Add(this.lblCountry);

                    

                CountryvalidationObject.Optional = true;
                CountryvalidationObject.Regex = "";
                CountryvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            CountryBindingObject.Data = "Country";
            CountryBindingObject.TwoWay = true;

            
                      this.txtCountry.Location = new System.Drawing.Point(150, 510);
                     
                    this.txtCountry.Size = new System.Drawing.Size(400, 39);
                     
                this.txtCountry.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtCountry.PlaceholderText = "Enter Country";
                this.txtCountry.ReadOnly = false;
                this.txtCountry.BackColor = System.Drawing.Color.White;
                 CountryvalidationObject.PropertyName = "Text";
                 CountryBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtCountry, CountryvalidationObject);
                this.bindingProvider.SetLink(this.txtCountry, CountryBindingObject);
                this.themeProvider.SetLink(this.txtCountry, null);
                this.pnlContent.Controls.Add(this.txtCountry);

                
                    //
                    // lblAddress1
                    //
                    this.lblAddress1.AutoSize = true;
                    this.lblAddress1.Location = new System.Drawing.Point(25, 590);
                    this.lblAddress1.Name = "lblAddress1";
                    this.lblAddress1.Text = "Address 1";
                    this.themeProvider.SetLink(this.lblAddress1, null);
                    this.pnlContent.Controls.Add(this.lblAddress1);

                    

                Address1validationObject.Optional = true;
                Address1validationObject.Regex = "(.|\\s)*\\S(.|\\s)*";
                Address1validationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            Address1BindingObject.Data = "Address1";
            Address1BindingObject.TwoWay = true;

            
                      this.txtAddress1.Location = new System.Drawing.Point(150, 580);
                     
                    this.txtAddress1.Size = new System.Drawing.Size(400, 39);
                     
                this.txtAddress1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtAddress1.PlaceholderText = "Enter Address1";
                this.txtAddress1.ReadOnly = false;
                this.txtAddress1.BackColor = System.Drawing.Color.White;
                 Address1validationObject.PropertyName = "Text";
                 Address1BindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtAddress1, Address1validationObject);
                this.bindingProvider.SetLink(this.txtAddress1, Address1BindingObject);
                this.themeProvider.SetLink(this.txtAddress1, null);
                this.pnlContent.Controls.Add(this.txtAddress1);

                
                    //
                    // lblAddress2
                    //
                    this.lblAddress2.AutoSize = true;
                    this.lblAddress2.Location = new System.Drawing.Point(25, 660);
                    this.lblAddress2.Name = "lblAddress2";
                    this.lblAddress2.Text = "Address 2";
                    this.themeProvider.SetLink(this.lblAddress2, null);
                    this.pnlContent.Controls.Add(this.lblAddress2);

                    

                Address2validationObject.Optional = true;
                Address2validationObject.Regex = "";
                Address2validationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            Address2BindingObject.Data = "Address2";
            Address2BindingObject.TwoWay = true;

            
                      this.txtAddress2.Location = new System.Drawing.Point(150, 650);
                     
                    this.txtAddress2.Size = new System.Drawing.Size(400, 39);
                     
                this.txtAddress2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtAddress2.PlaceholderText = "Enter Address2";
                this.txtAddress2.ReadOnly = false;
                this.txtAddress2.BackColor = System.Drawing.Color.White;
                 Address2validationObject.PropertyName = "Text";
                 Address2BindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtAddress2, Address2validationObject);
                this.bindingProvider.SetLink(this.txtAddress2, Address2BindingObject);
                this.themeProvider.SetLink(this.txtAddress2, null);
                this.pnlContent.Controls.Add(this.txtAddress2);

                
                    //
                    // lblType
                    //
                    this.lblType.AutoSize = true;
                    this.lblType.Location = new System.Drawing.Point(25, 730);
                    this.lblType.Name = "lblType";
                    this.lblType.Text = "Type*";
                    this.themeProvider.SetLink(this.lblType, null);
                    this.pnlContent.Controls.Add(this.lblType);

                    

                TypevalidationObject.Optional = false;
                TypevalidationObject.Regex = "";
                TypevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            TypeBindingObject.Data = "Type";
            TypeBindingObject.TwoWay = true;

            

                this.cmbType.Name = "cmbType";
                this.cmbType.Size = new System.Drawing.Size(400, 39);
                this.cmbType.Location = new System.Drawing.Point(150, 720);
	            this.cmbType.BackColor = System.Drawing.Color.White;
                this.cmbType.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.cmbType.Items.AddRange(new object[] {"Person","Company","Government","Partner","Organization","Other"});
                this.validationProvider.SetLink(this.cmbType, TypevalidationObject);
                 TypeBindingObject.Property = "Text";
                 this.bindingProvider.SetLink(this.cmbType, TypeBindingObject);
                this.themeProvider.SetLink(this.cmbType, null);
                this.pnlContent.Controls.Add(this.cmbType);
                 
                    //
                    // lblNotes
                    //
                    this.lblNotes.AutoSize = true;
                    this.lblNotes.Location = new System.Drawing.Point(25, 800);
                    this.lblNotes.Name = "lblNotes";
                    this.lblNotes.Text = "Notes";
                    this.themeProvider.SetLink(this.lblNotes, null);
                    this.pnlContent.Controls.Add(this.lblNotes);

                    

                NotesvalidationObject.Optional = true;
                NotesvalidationObject.Regex = "";
                NotesvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            NotesBindingObject.Data = "Notes";
            NotesBindingObject.TwoWay = true;

            
                      this.txtNotes.Location = new System.Drawing.Point(150, 790);
                     
                    this.txtNotes.Multiline=true;
                    this.txtNotes.Size = new System.Drawing.Size(400, 130);
                     
                this.txtNotes.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtNotes.PlaceholderText = "Enter Notes";
                this.txtNotes.ReadOnly = false;
                this.txtNotes.BackColor = System.Drawing.Color.White;
                 NotesvalidationObject.PropertyName = "Text";
                 NotesBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtNotes, NotesvalidationObject);
                this.bindingProvider.SetLink(this.txtNotes, NotesBindingObject);
                this.themeProvider.SetLink(this.txtNotes, null);
                this.pnlContent.Controls.Add(this.txtNotes);

                
                    //
                    // lblCreatedAt
                    //
                    this.lblCreatedAt.AutoSize = true;
                    this.lblCreatedAt.Location = new System.Drawing.Point(25, 970);
                    this.lblCreatedAt.Name = "lblCreatedAt";
                    this.lblCreatedAt.Text = "Created At*";
                    this.themeProvider.SetLink(this.lblCreatedAt, null);
                    this.pnlContent.Controls.Add(this.lblCreatedAt);

                    

                CreatedAtvalidationObject.Optional = false;
                CreatedAtvalidationObject.Regex = "";
                CreatedAtvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            CreatedAtBindingObject.Data = "CreatedAt";
            CreatedAtBindingObject.TwoWay = true;

            

                this.dtCreatedAt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.dtCreatedAt.BackColor = System.Drawing.Color.White;
                this.dtCreatedAt.BorderColor = System.Drawing.Color.Silver;
                this.dtCreatedAt.CalendarMonthBackground = System.Drawing.Color.White;
                this.dtCreatedAt.CalendarTitleBackColor = System.Drawing.Color.LightSteelBlue;
                this.dtCreatedAt.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
                this.dtCreatedAt.CalendarTrailingForeColor = System.Drawing.Color.Gray;
                this.dtCreatedAt.Color = System.Drawing.Color.Silver;
                this.dtCreatedAt.ForeColor = System.Drawing.Color.Black;
                this.dtCreatedAt.IconColor = System.Drawing.Color.Gray;
                this.dtCreatedAt.Location = new System.Drawing.Point(150, 960);
                this.dtCreatedAt.Name = "dtCreatedAt";
                this.dtCreatedAt.Size = new System.Drawing.Size(400, 32);
                this.dtCreatedAt.TabIndex = 14;

                 CreatedAtvalidationObject.PropertyName = "Value";
                 CreatedAtBindingObject.Property = "Value";
                this.validationProvider.SetLink(this.dtCreatedAt, CreatedAtvalidationObject);
                this.bindingProvider.SetLink(this.dtCreatedAt, CreatedAtBindingObject);
                this.pnlContent.Controls.Add(this.dtCreatedAt);
                this.themeProvider.SetLink(this.dtCreatedAt, null);
                
                     this.dtCreatedAt.Enabled=false;
                   
                    //
                    //lblBottom
                    //
                    this.lblBottom.AutoSize = true;
                    this.lblBottom.Location = new System.Drawing.Point(25, 1090);
                    this.lblBottom.Name = "lblBottom";
                    this.lblBottom.Text = "";
                    this.themeProvider.SetLink(this.lblBottom, null);
                    this.pnlContent.Controls.Add(this.lblBottom);

                    //code

			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.WhiteSmoke;
			this.ClientSize = new System.Drawing.Size(599, 573);
			this.MaximizeBox = false;
			this.Name = "Frm_Customer";
			this.Text = "Frm_Customer";
			this.DoubleBuffered = true;
			this.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Load += new System.EventHandler(this.Frm_Load);
			this.Controls.Add(this.pnlContent);
			this.Controls.Add(this.AppBar);
			this.pnlContent.Controls.Add(this.btnCancel);
			this.pnlContent.Controls.Add(this.btnAdd); 
			this.ResumeLayout(false);
			}

        #region  Jenga Generated Code
        public void JengaInit(Color themeColor)
        {
            AppBar.BackColor = themeColor; 
            foreach (Control ctrl in pnlContent.Controls)
            {
                if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuTextBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuTextBox)ctrl;
                    ctr.OnHoverState.BorderColor
                        = ctr.OnActiveState.BorderColor
                        = themeColor;

                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuDropdown))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuDropdown)ctrl;
                    ctr.ItemHighLightColor = themeColor;
                    ctr.ItemHighLightForeColor = Color.White;
                }
                else if (ctrl.GetType() == typeof(LinkLabel))
                {
                    var ctr = (LinkLabel)ctrl;
                    ctr.LinkColor
                        = ctr.VisitedLinkColor
                        = themeColor;
                }
                else if (ctrl.GetType() == typeof(Button))
                {
                    var ctr = (Button)ctrl;
                    ctr.FlatAppearance.BorderColor = themeColor;

                    if (ctr.Name == "btnAdd")
                        ctr.BackColor = themeColor;
                    else
                        ctr.ForeColor = themeColor;
                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuCheckBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuCheckBox)ctrl;
                    ctr.OnCheck.BorderColor = themeColor;
                    ctr.OnCheck.CheckBoxColor = themeColor;

                    ctr.OnUncheck.BorderColor = themeColor;
                    ctr.OnUncheck.CheckBoxColor = Color.WhiteSmoke;

                }

            }
        } 
        #endregion

			#endregion
			public Kimtoo.ValidationProvider.ValidationProvider validationProvider;
			public Kimtoo.BindingProvider.BindingProvider bindingProvider;
		    public Kimtoo.ThemeProvider.ThemeProvider themeProvider;
			public System.Windows.Forms.Button btnAdd;
			public System.Windows.Forms.Button btnCancel;
			public Bunifu.Utils.BunifuAppBar AppBar;
			public System.Windows.Forms.Panel pnlContent;
			public Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
			public Bunifu.UI.WinForms.BunifuSnackbar Alert;
		    public System.Windows.Forms.OpenFileDialog openFileDialog;
			public System.Windows.Forms.SaveFileDialog saveFileDialog;
			public System.Windows.Forms.Label lblName;
public Bunifu.UI.WinForms.BunifuTextBox txtName;
public System.Windows.Forms.Label lblPhone;
public Bunifu.UI.WinForms.BunifuTextBox txtPhone;
public System.Windows.Forms.Label lblEmail;
public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
public System.Windows.Forms.Label lblDepartment;
public Bunifu.UI.WinForms.BunifuTextBox txtDepartment;
public System.Windows.Forms.Label lblCity;
public Bunifu.UI.WinForms.BunifuTextBox txtCity;
public System.Windows.Forms.Label lblState;
public Bunifu.UI.WinForms.BunifuTextBox txtState;
public System.Windows.Forms.Label lblZip;
public Bunifu.UI.WinForms.BunifuTextBox txtZip;
public System.Windows.Forms.Label lblCountry;
public Bunifu.UI.WinForms.BunifuTextBox txtCountry;
public System.Windows.Forms.Label lblAddress1;
public Bunifu.UI.WinForms.BunifuTextBox txtAddress1;
public System.Windows.Forms.Label lblAddress2;
public Bunifu.UI.WinForms.BunifuTextBox txtAddress2;
public System.Windows.Forms.Label lblType;
  public Bunifu.UI.WinForms.BunifuDropdown cmbType;
public System.Windows.Forms.Label lblNotes;
public Bunifu.UI.WinForms.BunifuTextBox txtNotes;
public System.Windows.Forms.Label lblCreatedAt;
public Bunifu.UI.WinForms.BunifuDatePicker dtCreatedAt;
public System.Windows.Forms.Label lblBottom;
//declare
			}
			}