//Code Generated by Jenga.NET 
            using System.Drawing;
            using System.Windows.Forms;

			namespace CRM.Dialogs
			{
			partial class Frm_Member
			{

			private System.ComponentModel.IContainer components = null;

			protected override void Dispose(bool disposing)
			{
			if (disposing && (components != null))
			{
			components.Dispose();
			}
			base.Dispose(disposing);
			}

			#region Windows Form Designer generated code

			private void InitializeComponent()
			{
			this.components = new System.ComponentModel.Container();
			this.Alert = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
			this.validationProvider = new Kimtoo.ValidationProvider.ValidationProvider();
			this.bindingProvider = new Kimtoo.BindingProvider.BindingProvider();
            this.themeProvider = new Kimtoo.ThemeProvider.ThemeProvider();
			this.btnAdd = new System.Windows.Forms.Button();
			this.btnCancel = new System.Windows.Forms.Button();
			this.AppBar = new Bunifu.Utils.BunifuAppBar();
			this.pnlContent = new System.Windows.Forms.Panel();
			this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
		    this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
			this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
			this.lblPic = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject PicvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject PicBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.picPic = new System.Windows.Forms.PictureBox();
this.btnBrowsePic = new System.Windows.Forms.LinkLabel();
this.btnOpenPic = new System.Windows.Forms.LinkLabel();
this.lblName = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject NamevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject NameBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblGender = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject GendervalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject GenderBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.cmbGender = new Bunifu.UI.WinForms.BunifuDropdown();
this.lblEmail = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject EmailvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject EmailBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblTitle = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject TitlevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject TitleBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtTitle = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblDepartment = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject DepartmentvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject DepartmentBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtDepartment = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblRole = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject RolevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject RoleBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.cmbRole = new Bunifu.UI.WinForms.BunifuDropdown();
this.lblActive = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject ActivevalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject ActiveBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.chkActive = new Bunifu.UI.WinForms.BunifuCheckBox();
this.lblNotes = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject NotesvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject NotesBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.txtNotes = new Bunifu.UI.WinForms.BunifuTextBox();
this.lblCreatedAt = new System.Windows.Forms.Label();
 Kimtoo.ValidationProvider.ValidationObject CreatedAtvalidationObject = new Kimtoo.ValidationProvider.ValidationObject();
Kimtoo.BindingProvider.BindingProvider.BindingObject CreatedAtBindingObject = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
 this.dtCreatedAt = new Bunifu.UI.WinForms.BunifuDatePicker();
this.lblBottom = new System.Windows.Forms.Label();
//init

			this.SuspendLayout();
			//
			// AppBar
			//
			this.AppBar.BackColor = System.Drawing.Color.DodgerBlue;
			this.AppBar.ControlBoxColor = System.Drawing.Color.WhiteSmoke;
			this.AppBar.ControlBoxColorActive = System.Drawing.Color.White;
			this.AppBar.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
			this.AppBar.ForeColor = System.Drawing.Color.White;
			this.AppBar.Dock = System.Windows.Forms.DockStyle.Top;
			this.validationProvider.SetLink(this.AppBar, null);
			this.bindingProvider.SetLink(this.AppBar, null);
			this.AppBar.Location = new System.Drawing.Point(3, 5);
			this.AppBar.Name = "Member";
			this.AppBar.Size = new System.Drawing.Size(574, 46);
			this.AppBar.TabIndex = 6;
			this.AppBar.Title = "Member";
			this.AppBar.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
			//
			// pnlContent
			//
			this.pnlContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.validationProvider.SetLink(this.pnlContent, null);
			this.bindingProvider.SetLink(this.pnlContent, null);
			this.pnlContent.Location = new System.Drawing.Point(3, 51);
			this.pnlContent.Name = "pnlContent";
			this.pnlContent.Size = new System.Drawing.Size(590, 515);
			this.pnlContent.TabIndex = 7;
			this.pnlContent.AutoScroll = true;
			//
			// btnAdd
			//
			this.btnAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnAdd.BackColor = System.Drawing.Color.DodgerBlue;
			this.btnAdd.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
			this.btnAdd.FlatAppearance.BorderSize = 2;
			this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnAdd.ForeColor = System.Drawing.Color.White;
			this.validationProvider.SetLink(this.btnAdd, null);
			this.bindingProvider.SetLink(this.btnAdd, null);
			this.btnAdd.Location = new System.Drawing.Point(435, 1030);
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Size = new System.Drawing.Size(115, 40);
			this.btnAdd.TabIndex = 12;
			this.btnAdd.Text = "SAVE";
			this.btnAdd.UseVisualStyleBackColor = false;
			this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
			//
			// btnCancel
			//
			this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnCancel.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
			this.btnCancel.FlatAppearance.BorderSize = 2;
			this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnCancel.ForeColor = System.Drawing.Color.DodgerBlue;
			this.validationProvider.SetLink(this.btnCancel, null);
			this.bindingProvider.SetLink(this.btnCancel, null);
			this.btnCancel.Location = new System.Drawing.Point(335,  1030);
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.Size = new System.Drawing.Size(94, 40);
			this.btnCancel.TabIndex = 13;
			this.btnCancel.Text = "CANCEL";
			this.btnCancel.UseVisualStyleBackColor = false;
			this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
			//
			// bunifuFormDock
			//
			this.bunifuFormDock.AllowFormDragging = true;
			this.bunifuFormDock.AllowFormDropShadow = true;
			this.bunifuFormDock.AllowFormResizing = true;
			this.bunifuFormDock.AllowHidingBottomRegion = true;
			this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
			this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
			this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
			this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
			this.bunifuFormDock.ContainerControl = this;
			this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
			this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
			this.bunifuFormDock.DockingOptions.DockAll = true;
			this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
			this.bunifuFormDock.DockingOptions.DockBottomRight = true;
			this.bunifuFormDock.DockingOptions.DockFullScreen = true;
			this.bunifuFormDock.DockingOptions.DockLeft = true;
			this.bunifuFormDock.DockingOptions.DockRight = true;
			this.bunifuFormDock.DockingOptions.DockTopLeft = true;
			this.bunifuFormDock.DockingOptions.DockTopRight = true;
			this.bunifuFormDock.FormDraggingOpacity = 0.9D;
			this.bunifuFormDock.ParentForm = this;
			this.bunifuFormDock.ShowCursorChanges = true;
			this.bunifuFormDock.ShowDockingIndicators = true;
		    this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = false;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false; 
			//
			// Alert
			//
			this.Alert.AllowDragging = false;
			this.Alert.AllowMultipleViews = true;
			this.Alert.ClickToClose = true;
			this.Alert.DoubleClickToClose = true;
			this.Alert.DurationAfterIdle = 3000;
			this.Alert.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.ErrorOptions.ActionBorderRadius = 1;
			this.Alert.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.ErrorOptions.BackColor = System.Drawing.Color.White;
			this.Alert.ErrorOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
			this.Alert.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.ErrorOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.ErrorOptions.IconLeftMargin = 12;
			this.Alert.FadeCloseIcon = false;
			this.Alert.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
			this.Alert.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.ActionBorderRadius = 1;
			this.Alert.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.InformationOptions.BackColor = System.Drawing.Color.White;
			this.Alert.InformationOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
			this.Alert.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.InformationOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.InformationOptions.IconLeftMargin = 12;
			this.Alert.Margin = 10;
			this.Alert.MaximumSize = new System.Drawing.Size(0, 0);
			this.Alert.MaximumViews = 7;
			this.Alert.MessageRightMargin = 15;
			this.Alert.MinimumSize = new System.Drawing.Size(0, 0);
			this.Alert.ShowBorders = false;
			this.Alert.ShowCloseIcon = false;
			this.Alert.ShowIcon = true;
			this.Alert.ShowShadows = true;
			this.Alert.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.SuccessOptions.ActionBorderRadius = 1;
			this.Alert.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.SuccessOptions.BackColor = System.Drawing.Color.White;
			this.Alert.SuccessOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
			this.Alert.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.SuccessOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.SuccessOptions.IconLeftMargin = 12;
			this.Alert.ViewsMargin = 7;
			this.Alert.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.Alert.WarningOptions.ActionBorderRadius = 1;
			this.Alert.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
			this.Alert.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
			this.Alert.WarningOptions.BackColor = System.Drawing.Color.White;
			this.Alert.WarningOptions.BorderColor = System.Drawing.Color.White;
			this.Alert.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
			this.Alert.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
			this.Alert.WarningOptions.ForeColor = System.Drawing.Color.Black;
			this.Alert.WarningOptions.IconLeftMargin = 12;
			this.Alert.ZoomCloseIcon = true;

			
                    //
                    // lblPic
                    //
                    this.lblPic.AutoSize = true;
                    this.lblPic.Location = new System.Drawing.Point(25, 30);
                    this.lblPic.Name = "lblPic";
                    this.lblPic.Text = "Pic*";
                    this.themeProvider.SetLink(this.lblPic, null);
                    this.pnlContent.Controls.Add(this.lblPic);

                    

                PicvalidationObject.Optional = false;
                PicvalidationObject.Regex = "";
                PicvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            PicBindingObject.Data = "Pic";
            PicBindingObject.TwoWay = true;

            
                    this.picPic.Name = "picPic";
                    this.picPic.Location = new System.Drawing.Point(150, 28);
                    this.picPic.Size = new System.Drawing.Size(200, 200);
                    this.picPic.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
                    this.picPic.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
                    this.pnlContent.Controls.Add(this.picPic);
                    
                    this.btnBrowsePic.Location = new System.Drawing.Point(150, 240);
                    this.btnBrowsePic.Text = "🡅 Choose File";
                    this.btnBrowsePic.AutoSize = true;
                    this.btnBrowsePic.Name = "btnBrowsePic";
                    this.btnBrowsePic.Visible = true;
                    this.btnBrowsePic.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.btnBrowsePic_LinkClicked);
                    this.pnlContent.Controls.Add(this.btnBrowsePic);
                    
                    //
                    // btnOpenPic
                    //
                    this.btnOpenPic.AutoSize = true;
                    this.btnOpenPic.Location = new System.Drawing.Point(240, 240);
                    this.btnOpenPic.Name = "btnOpenPic";
                    this.btnOpenPic.Text = "🖿 Open";
                    this.btnOpenPic.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.btnOpenPic_LinkClicked);

                    this.pnlContent.Controls.Add(this.btnOpenPic);

                    
                    //
                    // lblName
                    //
                    this.lblName.AutoSize = true;
                    this.lblName.Location = new System.Drawing.Point(25, 300);
                    this.lblName.Name = "lblName";
                    this.lblName.Text = "Name*";
                    this.themeProvider.SetLink(this.lblName, null);
                    this.pnlContent.Controls.Add(this.lblName);

                    

                NamevalidationObject.Optional = false;
                NamevalidationObject.Regex = "^[a-z ,.'-]+$";
                NamevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            NameBindingObject.Data = "Name";
            NameBindingObject.TwoWay = true;

            
                      this.txtName.Location = new System.Drawing.Point(150, 290);
                     
                    this.txtName.Size = new System.Drawing.Size(400, 39);
                     
                this.txtName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtName.PlaceholderText = "Enter Name";
                this.txtName.ReadOnly = false;
                this.txtName.BackColor = System.Drawing.Color.White;
                 NamevalidationObject.PropertyName = "Text";
                 NameBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtName, NamevalidationObject);
                this.bindingProvider.SetLink(this.txtName, NameBindingObject);
                this.themeProvider.SetLink(this.txtName, null);
                this.pnlContent.Controls.Add(this.txtName);

                
                    //
                    // lblGender
                    //
                    this.lblGender.AutoSize = true;
                    this.lblGender.Location = new System.Drawing.Point(25, 370);
                    this.lblGender.Name = "lblGender";
                    this.lblGender.Text = "Gender*";
                    this.themeProvider.SetLink(this.lblGender, null);
                    this.pnlContent.Controls.Add(this.lblGender);

                    

                GendervalidationObject.Optional = false;
                GendervalidationObject.Regex = "";
                GendervalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            GenderBindingObject.Data = "Gender";
            GenderBindingObject.TwoWay = true;

            

                this.cmbGender.Name = "cmbGender";
                this.cmbGender.Size = new System.Drawing.Size(400, 39);
                this.cmbGender.Location = new System.Drawing.Point(150, 360);
	            this.cmbGender.BackColor = System.Drawing.Color.White;
                this.cmbGender.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.cmbGender.Items.AddRange(new object[] {"Male","Female","Non-Binary"});
                this.validationProvider.SetLink(this.cmbGender, GendervalidationObject);
                 GenderBindingObject.Property = "Text";
                 this.bindingProvider.SetLink(this.cmbGender, GenderBindingObject);
                this.themeProvider.SetLink(this.cmbGender, null);
                this.pnlContent.Controls.Add(this.cmbGender);
                 
                    //
                    // lblEmail
                    //
                    this.lblEmail.AutoSize = true;
                    this.lblEmail.Location = new System.Drawing.Point(25, 440);
                    this.lblEmail.Name = "lblEmail";
                    this.lblEmail.Text = "Email*";
                    this.themeProvider.SetLink(this.lblEmail, null);
                    this.pnlContent.Controls.Add(this.lblEmail);

                    

                EmailvalidationObject.Optional = false;
                EmailvalidationObject.Regex = "(?:[a-z0-9!#$%&'*+/=?^_`{|}'-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}'-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
                EmailvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            EmailBindingObject.Data = "Email";
            EmailBindingObject.TwoWay = true;

            
                      this.txtEmail.Location = new System.Drawing.Point(150, 430);
                     
                    this.txtEmail.Size = new System.Drawing.Size(400, 39);
                     
                this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtEmail.PlaceholderText = "Enter Email";
                this.txtEmail.ReadOnly = false;
                this.txtEmail.BackColor = System.Drawing.Color.White;
                 EmailvalidationObject.PropertyName = "Text";
                 EmailBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtEmail, EmailvalidationObject);
                this.bindingProvider.SetLink(this.txtEmail, EmailBindingObject);
                this.themeProvider.SetLink(this.txtEmail, null);
                this.pnlContent.Controls.Add(this.txtEmail);

                
                    //
                    // lblTitle
                    //
                    this.lblTitle.AutoSize = true;
                    this.lblTitle.Location = new System.Drawing.Point(25, 510);
                    this.lblTitle.Name = "lblTitle";
                    this.lblTitle.Text = "Title";
                    this.themeProvider.SetLink(this.lblTitle, null);
                    this.pnlContent.Controls.Add(this.lblTitle);

                    

                TitlevalidationObject.Optional = true;
                TitlevalidationObject.Regex = "";
                TitlevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            TitleBindingObject.Data = "Title";
            TitleBindingObject.TwoWay = true;

            
                      this.txtTitle.Location = new System.Drawing.Point(150, 500);
                     
                    this.txtTitle.Size = new System.Drawing.Size(400, 39);
                     
                this.txtTitle.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtTitle.PlaceholderText = "Enter Title";
                this.txtTitle.ReadOnly = false;
                this.txtTitle.BackColor = System.Drawing.Color.White;
                 TitlevalidationObject.PropertyName = "Text";
                 TitleBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtTitle, TitlevalidationObject);
                this.bindingProvider.SetLink(this.txtTitle, TitleBindingObject);
                this.themeProvider.SetLink(this.txtTitle, null);
                this.pnlContent.Controls.Add(this.txtTitle);

                
                    //
                    // lblDepartment
                    //
                    this.lblDepartment.AutoSize = true;
                    this.lblDepartment.Location = new System.Drawing.Point(25, 580);
                    this.lblDepartment.Name = "lblDepartment";
                    this.lblDepartment.Text = "Department";
                    this.themeProvider.SetLink(this.lblDepartment, null);
                    this.pnlContent.Controls.Add(this.lblDepartment);

                    

                DepartmentvalidationObject.Optional = true;
                DepartmentvalidationObject.Regex = "";
                DepartmentvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            DepartmentBindingObject.Data = "Department";
            DepartmentBindingObject.TwoWay = true;

            
                      this.txtDepartment.Location = new System.Drawing.Point(150, 570);
                     
                    this.txtDepartment.Size = new System.Drawing.Size(400, 39);
                     
                this.txtDepartment.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtDepartment.PlaceholderText = "Enter Department";
                this.txtDepartment.ReadOnly = false;
                this.txtDepartment.BackColor = System.Drawing.Color.White;
                 DepartmentvalidationObject.PropertyName = "Text";
                 DepartmentBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtDepartment, DepartmentvalidationObject);
                this.bindingProvider.SetLink(this.txtDepartment, DepartmentBindingObject);
                this.themeProvider.SetLink(this.txtDepartment, null);
                this.pnlContent.Controls.Add(this.txtDepartment);

                
                    //
                    // lblRole
                    //
                    this.lblRole.AutoSize = true;
                    this.lblRole.Location = new System.Drawing.Point(25, 650);
                    this.lblRole.Name = "lblRole";
                    this.lblRole.Text = "Role*";
                    this.themeProvider.SetLink(this.lblRole, null);
                    this.pnlContent.Controls.Add(this.lblRole);

                    

                RolevalidationObject.Optional = false;
                RolevalidationObject.Regex = "";
                RolevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            RoleBindingObject.Data = "Role";
            RoleBindingObject.TwoWay = true;

            

                this.cmbRole.Name = "cmbRole";
                this.cmbRole.Size = new System.Drawing.Size(400, 39);
                this.cmbRole.Location = new System.Drawing.Point(150, 640);
	            this.cmbRole.BackColor = System.Drawing.Color.White;
                this.cmbRole.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.cmbRole.Items.AddRange(new object[] {"Admin","Employee"});
                this.validationProvider.SetLink(this.cmbRole, RolevalidationObject);
                 RoleBindingObject.Property = "Text";
                 this.bindingProvider.SetLink(this.cmbRole, RoleBindingObject);
                this.themeProvider.SetLink(this.cmbRole, null);
                this.pnlContent.Controls.Add(this.cmbRole);
                 
                    //
                    // lblActive
                    //
                    this.lblActive.AutoSize = true;
                    this.lblActive.Location = new System.Drawing.Point(25, 720);
                    this.lblActive.Name = "lblActive";
                    this.lblActive.Text = "Active*";
                    this.themeProvider.SetLink(this.lblActive, null);
                    this.pnlContent.Controls.Add(this.lblActive);

                    

                ActivevalidationObject.Optional = false;
                ActivevalidationObject.Regex = "";
                ActivevalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            ActiveBindingObject.Data = "Active";
            ActiveBindingObject.TwoWay = true;

            
                this.chkActive.Location = new System.Drawing.Point(150, 718);
                this.chkActive.Checked = true;
                ActiveBindingObject.Property = "Checked";
                this.bindingProvider.SetLink(this.chkActive, ActiveBindingObject);
                this.themeProvider.SetLink(this.chkActive, null);
                this.pnlContent.Controls.Add(this.chkActive);

                
                    //
                    // lblNotes
                    //
                    this.lblNotes.AutoSize = true;
                    this.lblNotes.Location = new System.Drawing.Point(25, 790);
                    this.lblNotes.Name = "lblNotes";
                    this.lblNotes.Text = "Notes";
                    this.themeProvider.SetLink(this.lblNotes, null);
                    this.pnlContent.Controls.Add(this.lblNotes);

                    

                NotesvalidationObject.Optional = true;
                NotesvalidationObject.Regex = "";
                NotesvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            NotesBindingObject.Data = "Notes";
            NotesBindingObject.TwoWay = true;

            
                      this.txtNotes.Location = new System.Drawing.Point(150, 780);
                     
                    this.txtNotes.Multiline=true;
                    this.txtNotes.Size = new System.Drawing.Size(400, 130);
                     
                this.txtNotes.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.txtNotes.PlaceholderText = "Enter Notes";
                this.txtNotes.ReadOnly = false;
                this.txtNotes.BackColor = System.Drawing.Color.White;
                 NotesvalidationObject.PropertyName = "Text";
                 NotesBindingObject.Property = "Text";
                this.validationProvider.SetLink(this.txtNotes, NotesvalidationObject);
                this.bindingProvider.SetLink(this.txtNotes, NotesBindingObject);
                this.themeProvider.SetLink(this.txtNotes, null);
                this.pnlContent.Controls.Add(this.txtNotes);

                
                    //
                    // lblCreatedAt
                    //
                    this.lblCreatedAt.AutoSize = true;
                    this.lblCreatedAt.Location = new System.Drawing.Point(25, 960);
                    this.lblCreatedAt.Name = "lblCreatedAt";
                    this.lblCreatedAt.Text = "Created At*";
                    this.themeProvider.SetLink(this.lblCreatedAt, null);
                    this.pnlContent.Controls.Add(this.lblCreatedAt);

                    

                CreatedAtvalidationObject.Optional = false;
                CreatedAtvalidationObject.Regex = "";
                CreatedAtvalidationObject.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;

                
            CreatedAtBindingObject.Data = "CreatedAt";
            CreatedAtBindingObject.TwoWay = true;

            

                this.dtCreatedAt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
                this.dtCreatedAt.BackColor = System.Drawing.Color.White;
                this.dtCreatedAt.BorderColor = System.Drawing.Color.Silver;
                this.dtCreatedAt.CalendarMonthBackground = System.Drawing.Color.White;
                this.dtCreatedAt.CalendarTitleBackColor = System.Drawing.Color.LightSteelBlue;
                this.dtCreatedAt.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
                this.dtCreatedAt.CalendarTrailingForeColor = System.Drawing.Color.Gray;
                this.dtCreatedAt.Color = System.Drawing.Color.Silver;
                this.dtCreatedAt.ForeColor = System.Drawing.Color.Black;
                this.dtCreatedAt.IconColor = System.Drawing.Color.Gray;
                this.dtCreatedAt.Location = new System.Drawing.Point(150, 950);
                this.dtCreatedAt.Name = "dtCreatedAt";
                this.dtCreatedAt.Size = new System.Drawing.Size(400, 32);
                this.dtCreatedAt.TabIndex = 14;

                 CreatedAtvalidationObject.PropertyName = "Value";
                 CreatedAtBindingObject.Property = "Value";
                this.validationProvider.SetLink(this.dtCreatedAt, CreatedAtvalidationObject);
                this.bindingProvider.SetLink(this.dtCreatedAt, CreatedAtBindingObject);
                this.pnlContent.Controls.Add(this.dtCreatedAt);
                this.themeProvider.SetLink(this.dtCreatedAt, null);
                
                     this.dtCreatedAt.Enabled=false;
                   
                    //
                    //lblBottom
                    //
                    this.lblBottom.AutoSize = true;
                    this.lblBottom.Location = new System.Drawing.Point(25, 1080);
                    this.lblBottom.Name = "lblBottom";
                    this.lblBottom.Text = "";
                    this.themeProvider.SetLink(this.lblBottom, null);
                    this.pnlContent.Controls.Add(this.lblBottom);

                    //code
                    

			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.WhiteSmoke;
			this.ClientSize = new System.Drawing.Size(599, 573);
			this.MaximizeBox = false;
			this.Name = "Frm_Member";
			this.Text = "Frm_Member";
			this.DoubleBuffered = true;
			this.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Load += new System.EventHandler(this.Frm_Load);
			this.Controls.Add(this.pnlContent);
			this.Controls.Add(this.AppBar);
			this.pnlContent.Controls.Add(this.btnCancel);
			this.pnlContent.Controls.Add(this.btnAdd); 
			this.ResumeLayout(false);
			}

        #region  Jenga Generated Code
        public void JengaInit(Color themeColor)
        {
            AppBar.BackColor = themeColor; 
            foreach (Control ctrl in pnlContent.Controls)
            {
                if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuTextBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuTextBox)ctrl;
                    ctr.OnHoverState.BorderColor
                        = ctr.OnActiveState.BorderColor
                        = themeColor;

                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuDropdown))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuDropdown)ctrl;
                    ctr.ItemHighLightColor = themeColor;
                    ctr.ItemHighLightForeColor = Color.White;
                }
                else if (ctrl.GetType() == typeof(LinkLabel))
                {
                    var ctr = (LinkLabel)ctrl;
                    ctr.LinkColor
                        = ctr.VisitedLinkColor
                        = themeColor;
                }
                else if (ctrl.GetType() == typeof(Button))
                {
                    var ctr = (Button)ctrl;
                    ctr.FlatAppearance.BorderColor = themeColor;

                    if (ctr.Name == "btnAdd")
                        ctr.BackColor = themeColor;
                    else
                        ctr.ForeColor = themeColor;
                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuCheckBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuCheckBox)ctrl;
                    ctr.OnCheck.BorderColor = themeColor;
                    ctr.OnCheck.CheckBoxColor = themeColor;

                    ctr.OnUncheck.BorderColor = themeColor;
                    ctr.OnUncheck.CheckBoxColor = Color.WhiteSmoke;

                }

            }
        } 
        #endregion

			#endregion
			public Kimtoo.ValidationProvider.ValidationProvider validationProvider;
			public Kimtoo.BindingProvider.BindingProvider bindingProvider;
		    public Kimtoo.ThemeProvider.ThemeProvider themeProvider;
			public System.Windows.Forms.Button btnAdd;
			public System.Windows.Forms.Button btnCancel;
			public Bunifu.Utils.BunifuAppBar AppBar;
			public System.Windows.Forms.Panel pnlContent;
			public Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
			public Bunifu.UI.WinForms.BunifuSnackbar Alert;
		    public System.Windows.Forms.OpenFileDialog openFileDialog;
			public System.Windows.Forms.SaveFileDialog saveFileDialog;
			public System.Windows.Forms.Label lblPic;
private System.Windows.Forms.PictureBox picPic;
System.Windows.Forms.LinkLabel btnBrowsePic;
public System.Windows.Forms.LinkLabel btnOpenPic;
public System.Windows.Forms.Label lblName;
public Bunifu.UI.WinForms.BunifuTextBox txtName;
public System.Windows.Forms.Label lblGender;
  public Bunifu.UI.WinForms.BunifuDropdown cmbGender;
public System.Windows.Forms.Label lblEmail;
public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
public System.Windows.Forms.Label lblTitle;
public Bunifu.UI.WinForms.BunifuTextBox txtTitle;
public System.Windows.Forms.Label lblDepartment;
public Bunifu.UI.WinForms.BunifuTextBox txtDepartment;
public System.Windows.Forms.Label lblRole;
  public Bunifu.UI.WinForms.BunifuDropdown cmbRole;
public System.Windows.Forms.Label lblActive;
 public Bunifu.UI.WinForms.BunifuCheckBox chkActive;
public System.Windows.Forms.Label lblNotes;
public Bunifu.UI.WinForms.BunifuTextBox txtNotes;
public System.Windows.Forms.Label lblCreatedAt;
public Bunifu.UI.WinForms.BunifuDatePicker dtCreatedAt;
public System.Windows.Forms.Label lblBottom;
//declare
			}
			}